## This workflow performs PEP8 style checks on the python code in notebook code cells.
name: Notebook code PEP8 style check

on:
   pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.ipynb'
      - '*.yml'

jobs:
  NotebookExecutionValidation:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/pep8check_runner.yml@main
