## This workflow performs PEP8 style checks on the python code in notebook code cells.
name: PEP8 Notebook Style Check Execution

on:
   pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.py'
      - '*.yml'

jobs:
  NotebookExecutionValidation:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/script_pep8check.yml@main
