name: Python Style Checker

on: 
   pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.ipynb'
      - '*.yml'
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
